#!/usr/bin/env node

const { startVM, stopVM, setMachineType, getMetadata,
        getVM, sleepPromise, echoExec, getExternalIP } = require('./utils.js');

let addr = async function () {
  let vm = await getVM(process.argv[2]);
  let metadata = await getMetadata(vm);
  if (metadata.status !== "RUNNING") {
    await startVM(vm);
    while (metadata.status !== "RUNNING") {
      await sleepPromise(1000);
      metadata = await getMetadata(vm);
    }
  }
  let externalIP = getExternalIP(metadata);
  console.log(externalIP);
}

addr();