#!/usr/bin/node

/* jshint esnext:true */

const { startVM, stopVM, setMachineType, getMetadata,
        getVM, sleepPromise, echoExec, getExternalIP } = require('./utils.js');

let changeMachineType = async function (vm, machineType) {
  if (!(await getMetadata(vm)).machineType.endsWith("/" + machineType)) {
    console.log("stopping " + vm.name);
    await stopVM(vm);
    console.log("changing " + vm.name + " to " + machineType);
    await vm.resize(machineType);
    console.log("starting " + vm.name + " again");
  }
};

let runRemote = async function (vm, remoteCommand) {
  try {
    await startVM(vm);
    console.log(remoteCommand);
    // Obtain the external IP
    let metadata = await getMetadata(vm);
    let externalIP = getExternalIP(metadata);
    console.log("External IP: " + externalIP);
    console.log("Sleeping for 10 seconds");
    await sleepPromise(10000);
    if (remoteCommand.length > 0) {
        console.log("starting remote command...");
    	let commandToExecute = `ssh ${externalIP} "bash -c '${remoteCommand}'"`;
        console.log(commandToExecute);
        await echoExec(commandToExecute);
    } else {
        await echoExec(`ssh ${externalIP}`);
    }
    console.log(`stopping ${vm.name}`);
    await stopVM(vm);
    console.log("done");
  } catch (e) {
    console.log(e);
  }
};

let run = async function () {
  let localCommand = process.argv[2];
  let remoteCommand = process.argv.slice(3).join(" ");
  let vm = await getVM('instance-3');
  console.log(`${localCommand}, [${remoteCommand}]`);
  switch (localCommand) {
    case "fast":
    case "slow":
      // Change VM to requested cpu mode.
      let fast = localCommand === "fast";
      await changeMachineType(vm, fast ? "n1-highcpu-32" : "n1-standard-1");
      if (remoteCommand.length > 0) {
        await runRemote(vm, remoteCommand);
        if (fast) {
          // Save money by stopping after the remote command.
          await stopVM(vm);
        }
      } else {
        await startVM(vm);
      }
      break;
    case "stop":
      console.log(`stopping ${vm.name}`);
      await stopVM(vm);
      console.log("done");
      break;
  }
};

run();
